import './globals.css'
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import '../styles.css';
import { UserContextProvider } from '@/context/UserContext';
import { AuthContextProvider } from '@/context/AuthContext';

export const metadata = {
  title: 'B&H Barber Shop',
  description: 'Generated by ABX',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <AuthContextProvider>
            <UserContextProvider>
              <Nav />
              {children}
              <Footer />
            </UserContextProvider>
          </AuthContextProvider>
        </div>
      </body>
    </html>
  )
}
